source "https://rubygems.org"

gem "rake"
gem "serverspec"
gem "rspec-teamcity", "~> 0.0.1"
gem "nokogiri"
gem "octopus-serverspec-extensions", :git => "https://github.com/OctopusDeploy/octopus-serverspec-extensions.git"
