[ClassVersion("1.0.0"), FriendlyName("cOctopusWorkerPool")]
class cOctopusWorkerPool : OMI_BaseResource
{
  [Key] string Url;
  [Required, ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
  [Write] string WorkerPoolName;
  [Write] string WorkerPoolDescription;
  [Write] string SpaceID;
  [Write, EmbeddedInstance("MSFT_Credential")] string OctopusCredentials;
  [Write, EmbeddedInstance("MSFT_Credential")] string OctopusApiKey;
};
